// <auto-generated />
using System;
using AlertaClimatica.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlertaClimatica.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007191559_AgregarReglasAlerta")]
    partial class AgregarReglasAlerta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertaClimatica.Domain.Alerta", b =>
                {
                    b.Property<int>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlertaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertaId"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEmision");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mensaje");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NivelRiesgo");

                    b.Property<int?>("ReglaAlertaId")
                        .HasColumnType("int")
                        .HasColumnName("ReglaAlertaId");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("SensorId");

                    b.HasKey("AlertaId");

                    b.HasIndex("ReglaAlertaId");

                    b.HasIndex("SensorId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.Bitacora", b =>
                {
                    b.Property<long>("BitacoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BitacoraId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BitacoraId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Accion");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Detalle");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("BitacoraId");

                    b.ToTable("Bitacora", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.Comunidad", b =>
                {
                    b.Property<int>("ComunidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComunidadId"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComunidadId");

                    b.ToTable("Comunidades", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<string>("TipoFenomeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoEvento");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.LecturaClimatica", b =>
                {
                    b.Property<long>("LecturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LecturaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LecturaId"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("SensorId");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("LecturaId");

                    b.HasIndex("SensorId");

                    b.ToTable("LecturasClimaticas", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.ReglaAlerta", b =>
                {
                    b.Property<int>("ReglaAlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReglaAlertaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReglaAlertaId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mensaje");

                    b.Property<string>("NivelPeligro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NivelPeligro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.Property<string>("TipoFenomeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoFenomeno");

                    b.Property<int>("TipoSensorId")
                        .HasColumnType("int")
                        .HasColumnName("TipoSensorId");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorMaximo");

                    b.Property<decimal?>("ValorMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorMinimo");

                    b.HasKey("ReglaAlertaId");

                    b.HasIndex("TipoSensorId");

                    b.ToTable("ReglasAlerta", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreRol");

                    b.HasKey("RolId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComunidadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreSensor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoSensorId")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SensorId");

                    b.HasIndex("ComunidadId");

                    b.HasIndex("TipoSensorId");

                    b.ToTable("Sensores", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.TipoSensor", b =>
                {
                    b.Property<int>("TipoSensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoSensorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoSensorId"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreTipo");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UnidadMedida");

                    b.HasKey("TipoSensorId");

                    b.ToTable("TiposSensor", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ContraseniaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContraseniaHash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Correo");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoAcceso");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AlertaClimatica.Domain.Alerta", b =>
                {
                    b.HasOne("AlertaClimatica.Domain.ReglaAlerta", "ReglaAlerta")
                        .WithMany()
                        .HasForeignKey("ReglaAlertaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlertaClimatica.Domain.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReglaAlerta");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AlertaClimatica.Domain.LecturaClimatica", b =>
                {
                    b.HasOne("AlertaClimatica.Domain.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AlertaClimatica.Domain.ReglaAlerta", b =>
                {
                    b.HasOne("AlertaClimatica.Domain.TipoSensor", "TipoSensor")
                        .WithMany()
                        .HasForeignKey("TipoSensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoSensor");
                });

            modelBuilder.Entity("AlertaClimatica.Domain.Sensor", b =>
                {
                    b.HasOne("AlertaClimatica.Domain.Comunidad", "Comunidad")
                        .WithMany()
                        .HasForeignKey("ComunidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlertaClimatica.Domain.TipoSensor", "TipoSensor")
                        .WithMany()
                        .HasForeignKey("TipoSensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comunidad");

                    b.Navigation("TipoSensor");
                });
#pragma warning restore 612, 618
        }
    }
}
